server:
  port: 8765

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: core
          uri: lb://core
          predicates:
            - Path=/
        - id: pub
          uri: lb://pub
          predicates:
          - Path=/pub/**
  boot:
    admin:
      client:
        instance:
          management-base-url: http://localhost:8765/


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'