server:
  port: 8100

spring:
  application:
    name: pub

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka